[package]
name = "gcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-primitives = "0.4.2"
git2 = "0.18.1"
serde = { version = "1.0.192", features = ["derive"] }
sled = "0.34.7"
